"""initial schema

Revision ID: 14736a9fea83
Revises: 
Create Date: 2026-08-24 15:27:24.891917

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14736a9fea83'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.String(length=1024), nullable=True),
    sa.Column('new_value', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'CHECKBOX', 'DROPDOWN', name='field_control_type'), nullable=False),
    sa.Column('value_type', sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', name='field_value_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('system_field', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_definitions'))
    )
    op.create_index(op.f('ix_field_definitions_field_key'), 'field_definitions', ['field_key'], unique=True)
    op.create_table('inventory_view_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('visible_columns', sa.JSON(), nullable=False),
    sa.Column('column_order', sa.JSON(), nullable=False),
    sa.Column('sort_field', sa.String(length=64), nullable=True),
    sa.Column('sort_direction', sa.String(length=4), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_view_preferences'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('ammo_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('product_line', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_sku', sa.String(length=128), nullable=True),
    sa.Column('cartridge', sa.String(length=128), nullable=False),
    sa.Column('bullet_weight_gr', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('bullet_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low_stock_threshold_unit', sa.String(length=16), nullable=True),
    sa.Column('box_quantity', sa.Integer(), nullable=False),
    sa.Column('round_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['storage_location_id'], ['locations.id'], name=op.f('fk_ammo_products_storage_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ammo_products'))
    )
    op.create_table('dropdown_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('stable_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], name=op.f('fk_dropdown_options_field_definition_id_field_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dropdown_options')),
    sa.UniqueConstraint('field_definition_id', 'stable_key', name='uq_dropdown_option_field_key')
    )
    op.create_index(op.f('ix_dropdown_options_field_definition_id'), 'dropdown_options', ['field_definition_id'], unique=False)
    op.create_table('ammo_package_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammo_product_id', sa.Integer(), nullable=False),
    sa.Column('upc', sa.String(length=64), nullable=False),
    sa.Column('rounds_per_package', sa.Integer(), nullable=False),
    sa.Column('package_description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammo_product_id'], ['ammo_products.id'], name=op.f('fk_ammo_package_identifiers_ammo_product_id_ammo_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ammo_package_identifiers'))
    )
    op.create_index(op.f('ix_ammo_package_identifiers_ammo_product_id'), 'ammo_package_identifiers', ['ammo_product_id'], unique=False)
    op.create_index(op.f('ix_ammo_package_identifiers_upc'), 'ammo_package_identifiers', ['upc'], unique=True)
    op.create_table('custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammo_product_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('text_value', sa.String(length=1024), nullable=True),
    sa.Column('number_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ammo_product_id'], ['ammo_products.id'], name=op.f('fk_custom_field_values_ammo_product_id_ammo_products')),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], name=op.f('fk_custom_field_values_field_definition_id_field_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_values')),
    sa.UniqueConstraint('ammo_product_id', 'field_definition_id', name='uq_custom_field_value_product_field')
    )
    op.create_index(op.f('ix_custom_field_values_ammo_product_id'), 'custom_field_values', ['ammo_product_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_field_definition_id'), 'custom_field_values', ['field_definition_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.Column('barcode_format', sa.String(length=32), nullable=True),
    sa.Column('ammo_product_id', sa.Integer(), nullable=True),
    sa.Column('scanner_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'RESOLVED', 'COMPLETED', 'CANCELED', 'FAILED', name='scan_status'), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammo_product_id'], ['ammo_products.id'], name=op.f('fk_scan_events_ammo_product_id_ammo_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_events'))
    )
    op.create_index(op.f('ix_scan_events_payload'), 'scan_events', ['payload'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammo_product_id', sa.Integer(), nullable=False),
    sa.Column('scan_event_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('RECEIVE', 'REMOVE', 'ADJUST', name='transaction_type'), nullable=False),
    sa.Column('box_delta', sa.Integer(), nullable=False),
    sa.Column('round_delta', sa.Integer(), nullable=False),
    sa.Column('previous_box_balance', sa.Integer(), nullable=False),
    sa.Column('new_box_balance', sa.Integer(), nullable=False),
    sa.Column('previous_round_balance', sa.Integer(), nullable=False),
    sa.Column('new_round_balance', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('reverses_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammo_product_id'], ['ammo_products.id'], name=op.f('fk_inventory_transactions_ammo_product_id_ammo_products')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_inventory_transactions_location_id_locations')),
    sa.ForeignKeyConstraint(['reverses_transaction_id'], ['inventory_transactions.id'], name=op.f('fk_inventory_transactions_reverses_transaction_id_inventory_transactions')),
    sa.ForeignKeyConstraint(['scan_event_id'], ['scan_events.id'], name=op.f('fk_inventory_transactions_scan_event_id_scan_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions')),
    sa.UniqueConstraint('client_request_id', name=op.f('uq_inventory_transactions_client_request_id'))
    )
    op.create_index(op.f('ix_inventory_transactions_ammo_product_id'), 'inventory_transactions', ['ammo_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_ammo_product_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_scan_events_payload'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_custom_field_values_field_definition_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_ammo_product_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_ammo_package_identifiers_upc'), table_name='ammo_package_identifiers')
    op.drop_index(op.f('ix_ammo_package_identifiers_ammo_product_id'), table_name='ammo_package_identifiers')
    op.drop_table('ammo_package_identifiers')
    op.drop_index(op.f('ix_dropdown_options_field_definition_id'), table_name='dropdown_options')
    op.drop_table('dropdown_options')
    op.drop_table('ammo_products')
    op.drop_table('locations')
    op.drop_table('inventory_view_preferences')
    op.drop_index(op.f('ix_field_definitions_field_key'), table_name='field_definitions')
    op.drop_table('field_definitions')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
